config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'videos#index'
  
  as :user do
    get "/login" => "devise/sessions#new"
  end

  resources :videos, only: [:show]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
    @url = url
  end

  def url
    scan_data = @video.video_url.scan(/^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#\&\?]*).*/)
    scan_data[0][6]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videoportfolio</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body class="<%= "#{params[:controller]}-#{params[:action]}" %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>


  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="/">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            Log out
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<% @videos.each do |video| %>
    <div class="video_item">
      <%= link_to video_path(video) do %>
        <div class="preview_image" style="background-image: url('<%= video.preview %>');">
      <% end %>
      <div class="index_video_info">
        <div class="index_video_name">
          <p>
            <span class="highlight">Name:</span> <br>  
            <span class="indent"><%= link_to video.name, video_path(video) %></span>
          </p>
        </div>
        <div class="index_video_description">
          <p>
            <span class="highlight">Description:</span> <br>
            <span class="indent"><%= video.description %></span> 
          </p>
        </div>
      </div>
    </div>
<% end %>

app/views/videos/show.html.erb
<!-- Misschien een lege div class toevoegen met een hoogte die alleen zichtbaar is op xs zodat de video op 
kleine schermen meer in het midden wordt uitgelijnd -->

<div class="video_container">
  <!-- <div class="video_info">
    <div class="video_name">
      <%= @video.name %>
    </div>
    <div class="video_description">
      <%= @video.description %>
    </div>
  </div> -->
  <div class="video_wrapper">
    <iframe id="ytplayer" type="text/html" width="100%"
    src="https://www.youtube.com/embed/<%= @url %>?autoplay=1&fs=0&rel=0&showinfo=0"
    frameborder="0" allowfullscreen>
  </div>
</div>